import { TreatmentCategory } from '@/types/treatment';

export const TREATMENT_CATEGORIES: TreatmentCategory[] = [
  {
    id: 'corporais',
    label: 'Procedimentos Corporais',
    accent: 'teal',
    image: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?auto=format&fit=crop&w=800&q=80',
    description: 'Tratamentos para modelar, revitalizar e cuidar do corpo de forma completa.',
    items: [
      'Drenagem linfática',
      'Massagem modeladora',
      'Massagem relaxante',
      'Radiofrequência corporal',
      'Pump up (glúteos)',
      'Corrente russa',
      'Carboxiterapia',
      'Detox corporal',
      'Enzimas redutoras',
      'Tratamento para celulite',
      'Tratamento para estrias',
      'Tratamento para gordura localizada',
      'Laser a Luz Pulsada',
      'Peeling corporal',
      'Remoção de verrugas',
      'Depilação com cera',
    ],
  },
  {
    id: 'faciais',
    label: 'Procedimentos Faciais',
    accent: 'purple',
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&w=800&q=80',
    description: 'Protocolos avançados para limpeza, rejuvenescimento e harmonização facial.',
    items: [
      'Limpeza de pele profunda',
      'Peeling químico (mandélico, glicólico, salicílico, retinóico)',
      'Peeling de diamante',
      'Revitalização facial',
      'Microagulhamento',
      'Dermaplaning',
      'Máscaras hidratantes e calmantes',
      'Tratamento para acne',
      'Clareamento de manchas',
      'Rejuvenescimento facial',
      'Jato de plasma',
      'Sobrancelha (design, henna)',
    ],
  },
  {
    id: 'bem-estar',
    label: 'Estética e Bem Estar',
    accent: 'rose',
    image: 'https://images.unsplash.com/photo-1560750588-73207b1ef5b8?auto=format&fit=crop&w=800&q=80',
    description: 'Serviços completos de beleza e bem‑estar para o seu cuidado integral.',
    items: [
      'Manicure e pedicure',
      'Podologia',
      'Extensão de cílios',
      'Cabeleireira',
      'Bronze',
      'Psicóloga',
      'Tatuagens personalizadas',
      'Perfurações corporais e faciais (piercing)',
    ],
  },
  {
    id: 'avancada',
    label: 'Estética Avançada',
    accent: 'gold',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80',
    description: 'Procedimentos com tecnologia de ponta para resultados expressivos e duradouros.',
    items: [
      'Botox (toxina botulínica)',
      'Preenchimento labial',
      'Bioestimuladores',
    ],
  },
];
