/**
 * Remove Turbopack build artifacts from out/ after static export.
 * Runs automatically via "postbuild" in package.json.
 */

const fs = require('fs');
const path = require('path');

const OUT = path.join(process.cwd(), 'out');

function walk(dir) {
  if (!fs.existsSync(dir)) return;

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      // Remove entire Turbopack internal folders and redundant route folders
      if (
        entry.name.startsWith('__next.') ||
        entry.name === '_not-found' ||
        entry.name === '404'
      ) {
        fs.rmSync(full, { recursive: true, force: true });
      } else {
        walk(full);
      }
    } else {
      // Remove all .txt files generated by Turbopack
      if (entry.name.endsWith('.txt')) {
        fs.rmSync(full, { force: true });
      }
    }
  }
}

walk(OUT);
console.log('✓ out/ cleaned — Turbopack artifacts removed');
